# Generated by Django 5.1.2 on 2024-12-02 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitrationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('organization', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='resolvr.arbitrationcase')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolvr.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ArbitrationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('arbitration_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='resolvr.arbitrationcase')),
                ('arbitrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolvr.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='arbitrationcase',
            name='claimant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimant_cases', to='resolvr.userprofile'),
        ),
        migrations.AddField(
            model_name='arbitrationcase',
            name='respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respondent_cases', to='resolvr.userprofile'),
        ),
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict_text', models.TextField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('arbitration_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verdict', to='resolvr.arbitrationcase')),
                ('arbitrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolvr.userprofile')),
            ],
        ),
    ]
