# Generated by Django 5.1.2 on 2024-12-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolvr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='verdict',
            name='arbitration_case',
        ),
        migrations.RemoveField(
            model_name='arbitrationsession',
            name='arbitration_case',
        ),
        migrations.RemoveField(
            model_name='document',
            name='case',
        ),
        migrations.RemoveField(
            model_name='arbitrationsession',
            name='arbitrator',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='verdict',
            name='arbitrator',
        ),
        migrations.DeleteModel(
            name='ArbitrationCase',
        ),
        migrations.DeleteModel(
            name='ArbitrationSession',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='Verdict',
        ),
    ]
