# Generated by Django 5.1.2 on 2024-12-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolvr', '0006_userprofile_delete_contact_alter_case_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='details',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='case',
            name='documents',
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
